steps:
# Build the container that will do the go build.
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'builder', '-f', 'Dockerfile.build', '.']
# Do the go build.
  - name: 'builder'
    args: ['make', 'cross']
